import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useId} from 'react'

export default function Home() {

  //id variable
  const [id, setId] = useState(0);

  //string variable
  const [text, setText] = useState('');

  //string array
  const [todo, setTodo] = useState([]);

  //add to array function
  const add = (e) => {
    e.preventDefault();
    setId(id+1);
    const obj = {id: id, name: text};
    setTodo([obj, ...todo]);
    setText('');
  }

  //add to array function
  const deletion = (e) => {
    e.preventDefault();
    const name = e.target.getAttribute("name");
    setTodo(todo.filter(item => item.id.toString() !== name));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TO-DO LIST</title>
        <meta name="application to keep track of tasks" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1 className={styles.title}>TO-DO LIST</h1>

        <div className={styles.div}>
          <form>
            <input value={text} className={styles.input} onChange={e => setText(e.target.value)}></input>

            <button className={styles.button} onClick={add}>Add</button>

          </form>

        </div>

        <div className={styles.flexV}>
          {todo.map((item) => {
              return (
                <div className={styles.flex}>
                  <p className={styles.todo}>{item.name}</p>
                  <button className={styles.delete} name={item.id} onClick={deletion}>DEL</button>
                </div>
              )
            })}

        </div>
        
      </main>


     
    </div>
  )
}
